import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Shield, ChevronDown, ArrowLeft, Scale, Gavel, Heart, Clock, BookOpen, ExternalLink, Download, FileText } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';

const RIGHTS = [
  {
    id: 1, title: 'POSH Act Protection', subtitle: 'Sexual harassment prevention', icon: Shield,
    accent: '#ef4444', tintBg: '#fef2f2', tintText: '#b91c1c', tintBorder: 'rgba(239,68,68,0.22)',
    content: 'The POSH Act mandates every organization with 10 or more employees to constitute an Internal Complaints Committee (ICC). You have the right to a safe working environment, free from sexual harassment. Complaints can be filed within 3 months of the incident.',
    fullActUrl: 'https://legislative.gov.in/sites/default/files/A2013-14.pdf',
    actName: 'Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013',
    keyPoints: ['Mandatory ICC in all organizations with 10+ employees', 'Complaint filing within 3 months', 'Confidentiality of identity is mandatory', 'Employer liable for non-compliance'],
  },
  {
    id: 2, title: 'Maternity Benefits', subtitle: 'Paid leave & facilities', icon: Heart,
    accent: '#10b981', tintBg: '#ecfdf5', tintText: '#047857', tintBorder: 'rgba(16,185,129,0.22)',
    content: 'Women are entitled to 26 weeks of paid maternity leave for the first two children. Includes work from home provisions and mandatory creche facilities for 50+ employee establishments.',
    fullActUrl: 'https://labour.gov.in/sites/default/files/TheMaternityBenefitAct1961.pdf',
    actName: 'Maternity Benefit Act, 1961 (Amended 2017)',
    keyPoints: ['26 weeks paid leave for first two children', '12 weeks for third child onwards', 'Mandatory creche for 50+ employees', 'Work from home option post-maternity'],
  },
  {
    id: 3, title: 'Equal Remuneration', subtitle: 'Fair pay & no discrimination', icon: Gavel,
    accent: '#6366f1', tintBg: '#eef2ff', tintText: '#4338ca', tintBorder: 'rgba(99,102,241,0.22)',
    content: 'Employers must pay equal remuneration to men and women for same work. Discrimination in recruitment, promotion, training on grounds of sex is strictly prohibited.',
    fullActUrl: 'https://labour.gov.in/sites/default/files/equal_remuneration_act_1976_0.pdf',
    actName: 'Equal Remuneration Act, 1976 (Now under Code on Wages, 2019)',
    keyPoints: ['Equal pay for equal work', 'No discrimination in hiring', 'No discrimination in promotions', 'Penalties for non-compliance'],
  },
  {
    id: 4, title: 'Shift Regulations', subtitle: 'Safe working hours', icon: Clock,
    accent: '#f59e0b', tintBg: '#fffbeb', tintText: '#b45309', tintBorder: 'rgba(245,158,11,0.22)',
    content: 'Women cannot be required to work between 7 PM and 6 AM generally. In IT/ITeS sectors, night shifts allowed with adequate safety measures, transportation, and safe environment.',
    fullActUrl: 'https://labour.gov.in/sites/default/files/Factories_Act_1948.pdf',
    actName: 'Factories Act, 1948 (Section 66)',
    keyPoints: ['No night shifts without safety measures', 'Mandatory transport for night shifts', 'Safe restroom and rest facilities', 'Security guard escort required'],
  },
];

export default function KnowYourRights() {
  const navigate = useNavigate();
  const [expandedId, setExpandedId] = useState(null);
  const toggle = (id) => setExpandedId(expandedId === id ? null : id);

  const handleViewFullAct = (right) => {
    window.open(right.fullActUrl, '_blank', 'noopener,noreferrer');
    toast.success(`Opening ${right.title} document`);
  };

  const handleDownloadSummary = (right) => {
    const summaryText = `
═══════════════════════════════════════════
  ${right.title.toUpperCase()}
  ${right.actName}
═══════════════════════════════════════════

OVERVIEW
${'-'.repeat(40)}
${right.content}

KEY POINTS
${'-'.repeat(40)}
${right.keyPoints.map((p, i) => `  ${i + 1}. ${p}`).join('\n')}

IMPORTANT HELPLINES
${'-'.repeat(40)}
  • Women Helpline: 181
  • National Commission for Women: 7827-170-170
  • Legal Aid Services: 15100

═══════════════════════════════════════════
  Generated by She Care AI
  For legal advice, consult a qualified lawyer.
═══════════════════════════════════════════
`;

    const blob = new Blob([summaryText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${right.title.replace(/\s+/g, '_')}_Summary.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast.success('Summary downloaded!');
  };

  const cardStyle = {
    background: 'var(--color-surface-lowest)',
    borderRadius: '1.25rem',
    boxShadow: '0 1px 6px rgba(24,20,69,0.03)',
  };

  return (
    <div>
      <button
        onClick={() => navigate(-1)}
        style={{
          display: 'inline-flex', alignItems: 'center', gap: '4px',
          fontSize: '13px', color: 'var(--color-outline)', background: 'none',
          border: 'none', cursor: 'pointer', marginBottom: '16px',
          fontFamily: 'var(--font-sans)',
        }}
      >
        <ArrowLeft size={16} /> Back
      </button>

      {/* HERO */}
      <motion.div
        initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}
        style={{
          position: 'relative', borderRadius: '1.5rem', padding: '28px 24px',
          marginBottom: '18px', overflow: 'hidden',
          background: 'var(--color-surface-lowest)',
          boxShadow: '0 2px 16px rgba(24,20,69,0.04)',
        }}
      >
        <div style={{ position: 'absolute', top: '-60px', right: '-40px', width: '200px', height: '200px', background: 'rgba(99,102,241,0.08)', borderRadius: '50%', filter: 'blur(60px)', pointerEvents: 'none' }} />

        <div style={{ display: 'flex', alignItems: 'center', gap: '14px', position: 'relative', zIndex: 10 }}>
          <div style={{
            width: '52px', height: '52px', borderRadius: '16px',
            background: 'linear-gradient(135deg, #6366f1, #3b82f6)',
            display: 'flex', alignItems: 'center', justifyContent: 'center',
            boxShadow: '0 6px 20px rgba(99,102,241,0.25)',
          }}>
            <BookOpen size={24} color="white" strokeWidth={2.2} />
          </div>
          <div>
            <h1 style={{ fontSize: '24px', fontWeight: 800, fontFamily: 'var(--font-display)', color: 'var(--color-shakti-dark-text)', margin: 0, lineHeight: 1.2 }}>Know Your Rights</h1>
            <p style={{ fontSize: '13px', color: 'var(--color-outline)', margin: '3px 0 0' }}>Legal protections & workplace empowerment.</p>
          </div>
        </div>
      </motion.div>

      {/* Info Banner */}
      <div style={{
        background: '#ecfdf5', padding: '14px', borderRadius: '14px', marginBottom: '18px',
        display: 'flex', gap: '12px', alignItems: 'flex-start',
        border: '1px solid rgba(16,185,129,0.18)'
      }}>
        <div style={{
          width: '34px', height: '34px', borderRadius: '10px',
          background: 'rgba(16,185,129,0.12)', color: '#047857',
          display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0
        }}>
          <Scale size={16} />
        </div>
        <p style={{ fontSize: '13px', color: '#065f46', margin: 0, lineHeight: 1.5 }}>
          Knowledge is power. Below is a simplified summary of key protections.
          <span style={{ fontWeight: 700, color: '#4338ca' }}> For specific cases, always consult a legal professional.</span>
        </p>
      </div>

      {/* Rights Cards */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
        {RIGHTS.map((r) => {
          const Icon = r.icon;
          const open = expandedId === r.id;
          return (
            <motion.div key={r.id} layout style={cardStyle}>
              <button
                onClick={() => toggle(r.id)}
                style={{
                  width: '100%', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                  padding: '16px 18px', background: 'none', border: 'none', cursor: 'pointer',
                  textAlign: 'left', fontFamily: 'var(--font-sans)'
                }}
              >
                <div style={{ display: 'flex', alignItems: 'center', gap: '12px', minWidth: 0, flex: 1 }}>
                  <div style={{
                    width: '42px', height: '42px', borderRadius: '12px',
                    background: r.tintBg, color: r.accent,
                    display: 'flex', alignItems: 'center', justifyContent: 'center',
                    flexShrink: 0, border: `1px solid ${r.tintBorder}`
                  }}>
                    <Icon size={20} />
                  </div>
                  <div style={{ minWidth: 0 }}>
                    <h3 style={{ fontSize: '14px', fontWeight: 700, color: 'var(--color-shakti-dark-text)', margin: '0 0 2px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.title}</h3>
                    <p style={{ fontSize: '12px', color: 'var(--color-outline)', margin: 0 }}>{r.subtitle}</p>
                  </div>
                </div>
                <div style={{
                  width: '30px', height: '30px', borderRadius: '8px', flexShrink: 0,
                  background: open ? 'var(--color-shakti-dark-text)' : 'var(--color-surface-low)',
                  color: open ? 'white' : 'var(--color-outline)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  transition: 'all 0.2s', transform: open ? 'rotate(180deg)' : 'rotate(0deg)'
                }}>
                  <ChevronDown size={14} />
                </div>
              </button>

              <AnimatePresence>
                {open && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}
                    style={{ overflow: 'hidden' }}
                  >
                    <div style={{ padding: '4px 18px 18px', display: 'flex', flexDirection: 'column', gap: '14px' }}>
                      <p style={{
                        fontSize: '13px', color: 'var(--color-shakti-dark-text)', margin: 0, lineHeight: 1.6,
                        paddingLeft: '14px', borderLeft: `3px solid ${r.tintBorder}`
                      }}>
                        {r.content}
                      </p>

                      {/* Key Points */}
                      <div style={{
                        background: 'var(--color-surface-low)', borderRadius: '12px', padding: '14px',
                        border: '1px solid rgba(24,20,69,0.04)'
                      }}>
                        <p style={{ fontSize: '10px', fontWeight: 700, color: 'var(--color-outline)', textTransform: 'uppercase', letterSpacing: '0.08em', margin: '0 0 10px' }}>Key Points</p>
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                          {r.keyPoints.map((point, idx) => (
                            <div key={idx} style={{ display: 'flex', alignItems: 'flex-start', gap: '8px' }}>
                              <div style={{ width: '6px', height: '6px', borderRadius: '50%', background: r.accent, marginTop: '7px', flexShrink: 0 }} />
                              <span style={{ fontSize: '13px', color: 'var(--color-shakti-dark-text)', lineHeight: 1.5 }}>{point}</span>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Action Buttons */}
                      <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                        <button
                          onClick={() => handleViewFullAct(r)}
                          style={{
                            padding: '10px 14px', borderRadius: '10px',
                            background: r.tintBg, color: r.tintText,
                            border: `1px solid ${r.tintBorder}`,
                            fontSize: '12px', fontWeight: 700, cursor: 'pointer',
                            display: 'inline-flex', alignItems: 'center', gap: '6px',
                            fontFamily: 'var(--font-sans)'
                          }}
                        >
                          <ExternalLink size={13} /> View Full Act
                        </button>
                        <button
                          onClick={() => handleDownloadSummary(r)}
                          style={{
                            padding: '10px 14px', borderRadius: '10px',
                            background: 'var(--color-surface-low)', color: 'var(--color-outline)',
                            border: '1px solid rgba(24,20,69,0.05)',
                            fontSize: '12px', fontWeight: 700, cursor: 'pointer',
                            display: 'inline-flex', alignItems: 'center', gap: '6px',
                            fontFamily: 'var(--font-sans)'
                          }}
                        >
                          <Download size={13} /> Download Summary
                        </button>
                      </div>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </motion.div>
          );
        })}
      </div>

      {/* Legal Support CTA */}
      <motion.div
        initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}
        style={{
          marginTop: '20px', position: 'relative', overflow: 'hidden',
          borderRadius: '1.5rem', padding: '24px',
          background: 'linear-gradient(135deg, #6366f1, #a855f7)',
          boxShadow: '0 6px 24px rgba(99,102,241,0.18)'
        }}
      >
        <div style={{ position: 'absolute', top: '-40px', right: '-30px', width: '160px', height: '160px', background: 'rgba(255,255,255,0.15)', borderRadius: '50%', filter: 'blur(50px)', pointerEvents: 'none' }} />
        <div style={{ position: 'relative', zIndex: 10 }}>
          <h3 style={{ fontSize: '17px', fontWeight: 800, color: 'white', margin: '0 0 6px' }}>Legal Support Network</h3>
          <p style={{ fontSize: '13px', color: 'rgba(255,255,255,0.85)', margin: '0 0 16px', maxWidth: '420px', lineHeight: 1.5 }}>
            Connect with pro-bono lawyers and legal aid clinics specializing in women's workplace rights.
          </p>
          <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
            <button
              onClick={() => { window.open('https://nalsa.gov.in/', '_blank'); toast.success('Opening NALSA portal'); }}
              style={{
                padding: '10px 16px', borderRadius: '12px',
                background: 'white', color: '#4338ca',
                border: 'none', fontSize: '13px', fontWeight: 700,
                display: 'inline-flex', alignItems: 'center', gap: '6px',
                cursor: 'pointer', fontFamily: 'var(--font-sans)',
                boxShadow: '0 4px 10px rgba(0,0,0,0.06)'
              }}
            >
              <Scale size={14} /> Legal Aid Portal
            </button>
            <button
              onClick={() => { window.open('tel:15100'); toast.success('Calling Legal Aid: 15100'); }}
              style={{
                padding: '10px 16px', borderRadius: '12px',
                background: 'rgba(255,255,255,0.16)', color: 'white',
                border: '1px solid rgba(255,255,255,0.25)',
                fontSize: '13px', fontWeight: 700,
                display: 'inline-flex', alignItems: 'center', gap: '6px',
                cursor: 'pointer', fontFamily: 'var(--font-sans)'
              }}
            >
              <FileText size={14} /> Call 15100
            </button>
          </div>
        </div>
      </motion.div>
    </div>
  );
}
